import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/Navbar'

import '@radix-ui/themes/styles.css';
import { Theme, ThemePanel } from '@radix-ui/themes';
import '@radix-ui/themes/styles.css';
import './theme-config.css'

const inter = Inter(
  { subsets: ['latin'],
  variable: '--font-inter', 
})

export const metadata: Metadata = {
  title: 'Issues Apps',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.variable}>
      <Theme appearance="light" accentColor="purple" grayColor="sage" scaling="110%">
        <Navbar />
        <main className='p-5'>
        {children}
        </main>
        </Theme>

        </body>
    </html>
  )
}
